web:
  image: pdahse/nginx
  ports:
    - "81:80"
  volumes:
    - ./src/php/php_oauth_server/www:/var/www
    - ./src/nginx/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - phplocalhost
    - redis

php:
  image: nmcteam/php56
  volumes:
    - ./src/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src/php/php_oauth_server/www:/var/www
  links:
    - db
    - redis

db:
  image: sameersbn/mysql
  ports:
    - "3312:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - DB_NAME=test
    - DB_USER=php
    - DB_PASS=mysql

redis:
  image: redis
  hostname: redis
  ports:
    - "6379:6379"



